db_file: 'bot.db'

bot_url: 'https://t.me/golang_pocket_saver_bot'

messages:
  response:
    start: "Вітання! Щоб зберігати посилання у своєму Pocket акаунті, для початку тобі необхідно дати мені доступ. Для цього переходь за посиланням:\n%s"
    already_authorized: 'Ти вже авторизувався за допомогою свого Pocket облікового запису. Надсилай посилання щоб зберегти.'
    unknown_command: 'Я не знаю такої команди :('
    link_saved: 'Посилання успішно збережено!'
  error:
    default: 'Сталася невідома помилка.'
    invalid_url: 'Це невалідне посилання.'
    unable_to_save: 'Не вдалося зберегти посилання у Pocket. Спробуйте, будь ласка, пізніше.'
